name: Ruff format

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [main]
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@caf0cab7a618c569241d31dcd442f54681755d39 # v3
        with:
          version: "latest"

      - name: Ruff fmt
        run: uv run --group lint -- ruff format --diff
